name: advanced-mlops-workshop-env
dependencies:
- python=3.6.2
- pip
- pytorch
- pip:
  - numpy==1.15.4
  - pandas==0.23.4
  - scikit-learn==0.20.1
  - scipy==1.0.0
  - matplotlib==3.0.2
  - utils==0.9.0
  - torchvision==0.5.0
  - torchtext==0.5.0
  # Required packages for AzureML execution, history, and data preparation.
  - azureml-sdk==1.0.85
  - azureml-defaults==1.0.85
  - azure-cli==2.0.58
  # Dev Tools
  - setuptools
  - flake8
  - flake8_formatter_junit_xml
  - pytest